import asyncio
import logging

from database import db
from config import temp
from .test import CLIENT, start_clone_bot
from .utils import STS
from .topics import parse_fbatch_report
from .regix import forward, copy, custom_caption, media, msg_edit, TimeFormatter
from pyrogram import Client, filters
from pyrogram.errors import FloodWait
from pyrogram.types import InlineKeyboardButton, InlineKeyboardMarkup, KeyboardButton, ReplyKeyboardMarkup, ReplyKeyboardRemove

logger = logging.getLogger(__name__)
CLIENT = CLIENT()

_CHUNK = 190


async def _get_report_text(bot, message):
    """Ask the user for the /fbatch output, either pasted as text or
    uploaded as a .txt document, and return the raw text content."""
    ask = await bot.ask(
        message.chat.id,
        "<b>❪ TOPIC LINKS ❫</b>\n\n"
        "Send the <code>/fbatch</code> result file, or paste the topic "
        "First/Last links (or plain <code>START_LINK-END_LINK</code> lines, one per topic).\n\n"
        "/cancel - cancel this process",
    )
    if ask.text and ask.text.strip() == "/cancel":
        await ask.reply("<b>Process cancelled.</b>")
        return None

    if ask.document:
        try:
            path = await ask.download()
        except Exception as e:
            await ask.reply(f"<b>Could not download file:</b> <code>{e}</code>")
            return None
        try:
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                return f.read()
        finally:
            import os
            if os.path.exists(path):
                os.remove(path)

    return ask.text or ""


@Client.on_message(filters.private & filters.command(["fwdx"]))
async def fwdx_command(bot, message):
    user_id = message.from_user.id

    _bot = await db.get_bot(user_id)
    if not _bot:
        return await message.reply_text(
            "<b>You didn't add any bot. Please add a bot using /settings first.</b>"
        )

    channels = await db.get_user_channels(user_id)
    if not channels:
        return await message.reply_text(
            "<b>Please set a target chat in /settings before forwarding.</b>"
        )

    if len(channels) > 1:
        buttons, btn_data = [], {}
        for channel in channels:
            buttons.append([KeyboardButton(f"{channel['title']}")])
            btn_data[channel["title"]] = channel["chat_id"]
        buttons.append([KeyboardButton("cancel")])
        to_ask = await bot.ask(
            message.chat.id,
            "<b>Choose your target chat.</b>",
            reply_markup=ReplyKeyboardMarkup(buttons, one_time_keyboard=True, resize_keyboard=True),
        )
        if to_ask.text and to_ask.text.startswith(("/", "cancel")):
            return await message.reply_text("<b>Process cancelled.</b>", reply_markup=ReplyKeyboardRemove())
        toid = btn_data.get(to_ask.text)
        if not toid:
            return await message.reply_text("<b>Wrong channel chosen!</b>", reply_markup=ReplyKeyboardRemove())
    else:
        toid = channels[0]["chat_id"]

    report_text = await _get_report_text(bot, message)
    if report_text is None:
        return

    jobs = parse_fbatch_report(report_text)
    if not jobs:
        return await message.reply_text(
            "<b>Could not find any topic links in that input.</b>\n\n"
            "Send the file generated by /fbatch, or lines like:\n"
            "<code>https://t.me/c/CHATID/TOPIC/FIRSTMSG-https://t.me/c/CHATID/TOPIC/LASTMSG</code>"
        )

    total_ids = sum(j["last"] - j["first"] + 1 for j in jobs)
    summary = "\n".join(
        f"{idx + 1}. {j['name'] or ('Topic ' + str(j['topic_id']))} — "
        f"<code>{j['first']}</code> → <code>{j['last']}</code>"
        for idx, j in enumerate(jobs[:20])
    )
    if len(jobs) > 20:
        summary += f"\n...and {len(jobs) - 20} more"

    confirm = await message.reply_text(
        f"<b>❪ CONFIRM FORWARD ❫</b>\n\n"
        f"<b>Topics:</b> {len(jobs)}\n"
        f"<b>Total messages to scan:</b> {total_ids}\n\n"
        f"{summary}\n\n"
        f"<b>Start forwarding these topics to your target chat?</b>",
        reply_markup=InlineKeyboardMarkup([[
            InlineKeyboardButton("Yes", callback_data=f"fwdx_yes_{user_id}"),
            InlineKeyboardButton("No", callback_data="close_btn"),
        ]]),
    )

    temp.FWDX_JOBS[user_id] = {"jobs": jobs, "toid": toid, "msg_id": confirm.id}


@Client.on_callback_query(filters.regex(r"^fwdx_yes_"))
async def fwdx_confirm(bot, query):
    user_id = query.from_user.id
    data = temp.FWDX_JOBS.pop(user_id, None)
    if not data or data["msg_id"] != query.message.id:
        return await query.answer("This confirmation has expired. Send /fwdx again.", show_alert=True)

    if temp.lock.get(user_id) and str(temp.lock.get(user_id)) == "True":
        return await query.answer("Please wait until your previous task completes.", show_alert=True)

    toid = data["toid"]
    if toid in temp.IS_FRWD_CHAT:
        return await query.answer("A task is already running for this target chat. Please wait.", show_alert=True)

    await query.answer()
    m = await query.message.edit_text("<code>Verifying your data, please wait...</code>")

    _bot = await db.get_bot(user_id)
    try:
        client = await start_clone_bot(CLIENT.client(_bot))
    except Exception as e:
        return await m.edit(f"<b>Error starting your bot/userbot:</b> <code>{e}</code>")

    try:
        k = await client.send_message(toid, "Testing")
        await k.delete()
    except Exception:
        await m.edit(
            "<b>Please make your bot/userbot admin in the target channel with full permissions.</b>"
        )
        return await _stop(client, user_id)

    jobs = data["jobs"]
    sts = STS(f"fwdx-{user_id}")
    sts.store(None, toid, 0, sum(j["last"] - j["first"] + 1 for j in jobs))

    configs = await db.get_configs(user_id)
    caption = configs["caption"]
    forward_tag = configs["forward_tag"]
    protect = configs["protect"]
    from .test import parse_buttons
    button = parse_buttons(configs["button"] if configs["button"] else "")

    temp.forwardings += 1
    await db.add_frwd(user_id)
    temp.IS_FRWD_CHAT.append(toid)
    temp.lock[user_id] = True

    sleep = 0.5 if _bot["is_bot"] else 3
    fetched = total_files = deleted = 0

    try:
        for j_idx, job in enumerate(jobs):
            chat_ref = job["chat_ref"]
            first, last = job["first"], job["last"]
            name = job["name"] or f"Topic {job['topic_id']}"
            sts.data[sts.id]["FROM"] = chat_ref

            try:
                await m.edit(
                    f"<b>Forwarding topic {j_idx + 1}/{len(jobs)}:</b> {name}\n"
                    f"<code>{first}</code> → <code>{last}</code>\n\n"
                    f"Fetched: {fetched} | Forwarded: {total_files} | Deleted: {deleted}"
                )
            except Exception:
                pass

            MSG = []
            for chunk_start in range(first, last + 1, _CHUNK):
                if temp.CANCEL.get(user_id) is True:
                    raise asyncio.CancelledError("cancelled by user")

                ids = list(range(chunk_start, min(chunk_start + _CHUNK, last + 1)))
                try:
                    result = await client.get_messages(chat_ref, ids)
                    msgs = result if isinstance(result, list) else [result]
                except FloodWait as e:
                    await asyncio.sleep(e.value + 1)
                    continue
                except Exception as e:
                    logger.warning(f"fwdx get_messages error: {e}")
                    await asyncio.sleep(1.5)
                    continue

                for msg in msgs:
                    fetched += 1
                    if msg is None or getattr(msg, "empty", True) or msg.service:
                        deleted += 1
                        continue
                    if getattr(msg, "forum_topic_created", None) is not None:
                        continue
                    if not msg.media:
                        continue

                    if not caption:
                        MSG.append(msg.id)
                        if len(MSG) >= 100:
                            await forward(client, MSG, m, sts, protect, drop_author=not forward_tag)
                            total_files += len(MSG)
                            MSG = []
                            await asyncio.sleep(3)
                    else:
                        details = {
                            "msg_id": msg.id,
                            "media": media(msg),
                            "caption": custom_caption(msg, caption),
                            "button": button,
                            "protect": protect,
                        }
                        details["from_chat"] = chat_ref
                        await _copy_from(client, chat_ref, details, m, sts, toid)
                        total_files += 1
                        await asyncio.sleep(sleep)

                try:
                    await m.edit(
                        f"<b>Forwarding topic {j_idx + 1}/{len(jobs)}:</b> {name}\n"
                        f"<code>{first}</code> → <code>{last}</code>\n\n"
                        f"Fetched: {fetched} | Forwarded: {total_files} | Deleted: {deleted}"
                    )
                except Exception:
                    pass
                await asyncio.sleep(0.35)

            if MSG:
                await forward(client, MSG, m, sts, protect, drop_author=not forward_tag)
                total_files += len(MSG)
                MSG = []
                await asyncio.sleep(3)

    except asyncio.CancelledError:
        try:
            await m.edit(
                f"<b>❌ Forwarding cancelled.</b>\n\n"
                f"Fetched: {fetched} | Forwarded: {total_files} | Deleted: {deleted}"
            )
        except Exception:
            pass
        temp.CANCEL[user_id] = False
        return await _stop(client, user_id, toid)
    except Exception as e:
        logger.error(f"fwdx forward error: {e}")
        try:
            await m.edit(f"<b>Error:</b> <code>{e}</code>")
        except Exception:
            pass
        return await _stop(client, user_id, toid)

    try:
        await m.edit(
            f"<b>🎉 Forwarding completed!</b>\n\n"
            f"Topics: {len(jobs)}\n"
            f"Fetched: {fetched} | Forwarded: {total_files} | Deleted: {deleted}"
        )
    except Exception:
        pass
    await _stop(client, user_id, toid)


async def _copy_from(bot, from_chat, details, m, sts, toid):
    try:
        if details.get("media") and details.get("caption"):
            await bot.send_cached_media(
                chat_id=toid,
                file_id=details["media"],
                caption=details["caption"],
                reply_markup=details["button"],
                protect_content=details["protect"],
            )
        else:
            await bot.copy_message(
                chat_id=toid,
                from_chat_id=from_chat,
                caption=details.get("caption"),
                message_id=details["msg_id"],
                reply_markup=details["button"],
                protect_content=details["protect"],
            )
    except FloodWait as e:
        await asyncio.sleep(e.value)
        await _copy_from(bot, from_chat, details, m, sts, toid)
    except Exception as e:
        logger.warning(f"fwdx copy error: {e}")


async def _stop(client, user_id, toid=None):
    try:
        await client.stop()
    except Exception:
        pass
    await db.rmve_frwd(user_id)
    temp.forwardings -= 1
    temp.lock[user_id] = False
    if toid is not None and toid in temp.IS_FRWD_CHAT:
        temp.IS_FRWD_CHAT.remove(toid)

